os: linux
arch:
 - amd64
 - ppc64le

language: python
cache: pip

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  
matrix:
  exclude:
  - arch: ppc64le
    python: 3.3  

install:
    - pip install -r requirements.txt

script:
    - ./runtests
